### PR TITLE
Android-to-welcome-page

### PR DESCRIPTION
**Pull request by Ivana-Markovic**
adding android to welcome page

### CODE REVIEW

**Comment by shiroyasha** [comment]
Android is not a programming language. I feel we need a new section for this.

**Comment by Ivana-Markovic** [comment]
It currently belongs to the programming languages category, but np, I won't merge this pull request @shiroyasha

**Comment by markoa** [comment]
I originally introduced it to the PL section because others are less fitting and it's how other providers categorize it.

**Comment by shiroyasha** [comment]
I suggest a new section on this page with:

title: CI/CD Environments

- Linux
- MacOS
- IOS
- Android
- Use your own CI/CD Docker image

 I separated MacOS and IOS on purpose.

**Comment by Ivana-Markovic** [comment]
I will create an IP for Pera based on https://github.com/semaphoreci/docs/pull/636#issuecomment-568705451

**Comment by shiroyasha** [comment]
@Ivana-Markovic this seems like an outdated PR. Should we close it?

**Comment by Ivana-Markovic** [comment]
@shiroyasha I still think we should add Android to our welcome page in docs as it deserves. It is still in Programming languages (even after Darko's restructuring).

Do you maybe have a better idea where I can add Android here: https://docs.semaphoreci.com/ , since you do not think under 'Language specific configuration' is the right place?

**Comment by shiroyasha** [comment]
I agree Android needs to be mentioned.

I'll come back with a full proposal by the end of the week.

**Comment by shiroyasha** [comment]
I promised it, but I haven't delivered. Sorry for prolonging this effort.

For the CI/CD envs, I creader a dedicated PR. https://github.com/semaphoreci/docs/pull/778.

Rebasing and merging this as it is.

**Pull request merged**
