### PR TITLE
redirects

### PR DESCRIPTION
**Pull request by Ivana-Markovic**

### CODE REVIEW

**Comment by CommanderK5** [comment]
There is a duplicated entry and this will break nginx:
```

2019/12/20 09:28:41 [emerg] 1#1: duplicate location "/article/124-ios-continuous-integration-xcode" in /etc/nginx/conf.d/default.conf:131
--
```

**Comment by Ivana-Markovic** [comment]
well spotted @CommanderK5  🙇‍♀️👏, fixed this.

**Comment by CommanderK5** [comment]
another one: 
```
nginx: [emerg] duplicate location "/article/78-working-with-docker-images" in /etc/nginx/conf.d/default.conf:83
```

**Comment by Ivana-Markovic** [comment]
@CommanderK5 I checked for all duplicates and there should be none, please try now 🤞

**Pull request merged**
