### PR TITLE
Project Insights 

### PR DESCRIPTION
**Pull request by ralopes**
image

### CODE REVIEW

**Review by lucianoliberti — APPROVED** [review]

**Review by skipi — APPROVED** [review]
:shipit:

**Review by markoa — CHANGES_REQUESTED** [review]
Hey guys, I have some feedback about the copy in docs and UI. Mainly the point is to shift the tone from apologizing to positive.

In UI:

- "Unfortunately, there is no data..." → remove all occurences of "unfortunately" in UI copy.
- "This is a technical preview build." → what is a build?? Perhaps you meant "this feature is in technical preview".

In docs:
- "The feature is still in Tech Preview" → remove the unnecessary word 'still'.
- What is the reason of putting "Default behavior" section (which could be renamed to "Default data retention") to the very beginning? Seems like it could easily be at the very bottom. We want to showcase the good stuff as high as possible. 
    - For this reason, consider removing the "No data" section. It doesn't teach the user anything.
- "You will see the following message" → the UI message can change over time, you can just say that the user will see "the page without data", for example.
- I noticed mention of "build runs" - this is not an official concept in S2.
- "Configuring insights" - the intro could be more explicit about what it's trying to say, which is that Semaphore tracks CI insights out of the box, and CD needs to be configured.
- Avoid passive voice, eg. "After changes are saved" → "After you save changes".
- "More information"
    - in general I think that linking to a blog post for more info is a red flag. Blog posts are snapshots in time, docs are supposed to be maintained and kept up to date with all the info that is useful.
    - "if you'd like to know more about DORA..." - this is the first time DORA is mentioned on the entire page, it's unclear why this sentence is here.

**Comment by lucianoliberti** [comment]
@markoa thanks for your review! Btw, do we need to add the Copy Writer to review this doc?

**Comment by ralopes** [comment]
> Hey guys, I have some feedback about the copy in docs and UI. Mainly the point is to shift the tone from apologizing to positive.
> 
> In UI:
> 
>     * "Unfortunately, there is no data..." → remove all occurences of "unfortunately" in UI copy.
> 
>     * "This is a technical preview build." → what is a build?? Perhaps you meant "this feature is in technical preview".
> 
> 
> In docs:
> 
>     * "The feature is still in Tech Preview" → remove the unnecessary word 'still'.
> 
>     * What is the reason of putting "Default behavior" section (which could be renamed to "Default data retention") to the very beginning? Seems like it could easily be at the very bottom. We want to showcase the good stuff as high as possible.
>       
>       * For this reason, consider removing the "No data" section. It doesn't teach the user anything.
> 
>     * "You will see the following message" → the UI message can change over time, you can just say that the user will see "the page without data", for example.
> 
>     * I noticed mention of "build runs" - this is not an official concept in S2.
> 
>     * "Configuring insights" - the intro could be more explicit about what it's trying to say, which is that Semaphore tracks CI insights out of the box, and CD needs to be configured.
> 
>     * Avoid passive voice, eg. "After changes are saved" → "After you save changes".
> 
>     * "More information"
>       
>       * in general I think that linking to a blog post for more info is a red flag. Blog posts are snapshots in time, docs are supposed to be maintained and kept up to date with all the info that is useful.
>       * "if you'd like to know more about DORA..." - this is the first time DORA is mentioned on the entire page, it's unclear why this sentence is here.

I've removed more information section, updated the UI (copy changes were deployed to production), and changed the copy text in the documentation as well.

**Review by markoa — APPROVED** [review]
Great, thanks @ralopes!

@lucianoliberti Let's have a copywriter review whenever we introduce a new page, or make a substantial addition to an existing one.

**Pull request merged**
