### PR TITLE
Add docs for auto_promote using Conditions DSL

### PR DESCRIPTION
**Pull request by DamjanBecirovic**

### CODE REVIEW

**Comment by markoa** [comment]
@shiroyasha ping, we need this to complete the changelog entry for the week. #541

**Comment by markoa** [comment]
Should we also update the [intro to deployment](https://docs.semaphoreci.com/article/67-deploying-with-promotions) in guided tour? If yes @DamjanBecirovic can you replace the current examples with the new syntax?

**Comment by DamjanBecirovic** [comment]
We should eventually change all the examples of the previous syntax in docs with a new one, but maybe for the beginning only that one would be ok.

I'll change this one now, and later open the issue for updating the rest of the examples.

**Comment by markoa** [comment]
Sounds good, thanks.

**Pull request merged**
