### PR TITLE
Go CI

### LINKED ISSUE #289: Go CI demo
Go Continuous Integration demo

### PR DESCRIPTION
**Pull request by mactsouk**
Closes #289.

### CODE REVIEW

**Comment by mactsouk** [comment]
Closes #289.

**Comment by mactsouk** [comment]
@markoa Thanks for the feedback - I have addressed your comments.

**Comment by markoa** [comment]
@mactsouk Great! There are just a few formatting details to fix in the "explaining" section (around links). Please take a look and we'll merge.

**Comment by mactsouk** [comment]
@markoa It should be OK. Please merge.

**Pull request merged**
