### PR TITLE
add a bit about restricting access to a secret

### PR DESCRIPTION
**Pull request by hamir-suspect**

### CODE REVIEW

**Comment by radwo** [comment]
@csidyel, can you check it?

**Comment by csidyel** [comment]
> @csidyel, can you check it?

I talked with @hamir-suspect yesterday about it.

**Comment by lucianoliberti** [comment]
@hamir-suspect please don't merge this doc until it's reviewed by the [Copy Writer](https://github.com/Charismatron). As soon as he has access I'll add him as a reviewer. Thanks

**Review by Charismatron — APPROVED** [review]
I merged edits.

**Pull request merged**
